### ISSUE TITLE
Smooth Stone crafting recipe

### ISSUE THREAD

**Issue by Jaketron6252** [oitsjustjose/1.12.2-Public-Pack#2]
Smooth stone is lacking a crafting recipe. Putting stone into a furnace produces Circuit Plates from ProjectRed

**Comment by oitsjustjose** [comment]
Honestly I didn't even realize smooth stone was at thing in this version 😅

**Comment by lukachukai1** [comment]
it is because of quark

**Comment by lukachukai1** [comment]
i think

**Comment by lukachukai1** [comment]
and sub aquatic

**Comment by oitsjustjose** [comment]
Yeah that tracks. Ok - working on the pack updates right now anyways so I'll get that fixed up :)

**Comment by lukachukai1** [comment]
Thanks!

**Comment by lukachukai1** [comment]
this issue should be closed
