### ISSUE TITLE
No crafting recipe for reactor casing (extreme reactors)

### ISSUE THREAD

**Issue by lukachukai1** [oitsjustjose/1.12.2-Public-Pack#3]

**Comment by lukachukai1** [comment]
You need graphite to make any of the extreme reactor blocks

**Comment by oitsjustjose** [comment]
Fixed by https://github.com/oitsjustjose/1.12.2-Public-Pack/commit/c7bb0d5ff0695c7b6facdffb22e36bfe3bc95513
